region: us-east-1
role_arn: arn:aws:iam::474281778567:role/LabRole
lambda_function_name: CsvToJsonConverter
lambda_handler: dist/index.handler
lambda_runtime: nodejs18.x
zip_file: lambda_function_payload.zip
lambda_file: dist/index.js
